### ISSUE TITLE
An example of a working project

### ISSUE THREAD

**Issue by eddyekofo94** [rudibech/parcel-aspnetcore#2]
Hi,
I would like to try this, one thing that would be great is a sample working project to have it running and see how it works. 

Thank you.

**Comment by benpolinsky** [comment]
Yeah, it's really not very clear how to actually run a project.

**Comment by rudibech** [comment]
Thanks for the feedback. Is the documentation unclear? Is it difficult to create such a sample project yourself?

I'll consider adding a sample project the next time I need to change something, but I am afraid that any sample project might just as easily become a distraction.
